#version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: commerce-mysql-local
    ports:
      - "13336:3306"
    env_file:
      - .env.local
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./mysql-data-local:/var/lib/mysql

  redis:
    image: redis:7.4
    container_name: commerce-redis-local
    ports:
      - "16379:6379"

  kafka:
    image: apache/kafka:4.1.1
    container_name: commerce-kafka-local
    ports:
      - "127.0.0.1:19092:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      # Kafka가 컨테이너 내부에서 리슨하는 포트 (bootstrap)
      # - INTERNAL(9092): 도커 네트워크 내부 컨테이너용
      # - CONTROLLER(9093): KRaft 컨트롤러 통신용
      # - EXTERNAL(9094): 컨테이너 내부 외부용 리스너 포트
      KAFKA_LISTENERS: INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      # 클라이언트에게 안내할 주소
      # - 도커 네트워크 내부 컨테이너: kafka:9092 (commerce-kafka-local:9092는 도커 네트워크로 묶는다면 이런식으로 명시함(배포환경), 현재는 compose파일에 있는 것만 하기 때문에 패스)
      # - 호스트(맥북 로컬 앱): localhost:19092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      # 단일 브로커 로컬 개발용
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      # KRaft 클러스터 ID (한 번 정하면 유지)
      KAFKA_CLUSTER_ID: abcdefghijklmnopqrstuv
      # LOG 저장소 위치 지정
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
    volumes:
      - ./kafka-data-local:/tmp/kraft-combined-logs
