#version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: commerce-mysql-local
    ports:
      - "13336:3306"
    env_file:
      - .env.local
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./mysql-data-local:/var/lib/mysql
