spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

logging:
  level:
    root: WARN

jwt:
  access:
    secret.key: testAccessSecretKey0123456789abcdef!!
    expiration: 1800000
  refresh:
    secret.key: testRefreshSecretKey0123456789abcdef!!
    expiration: 604800000
